'use client';
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider, createTheme } from '@mui/material';
import YourAppBar from '../components/appBar';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] })

interface LayoutProps {
  children: ReactNode;
}

const metadata = {
  title: 'CRM',
  description: 'Generated by create next app',
}

const theme = createTheme();

const Layout: React.FC<LayoutProps> = ({ children }) => {
  {
    return (
      <html lang="en">
        <body className={inter.className}>
        <ThemeProvider theme={theme}>
         <YourAppBar />
  
         <main style={{ display: 'flex', minHeight: '100vh', flexDirection: 'column', alignItems: 'flex-start', padding: 0 }}>
           <div style={{ margin: '0 auto', marginTop: 0 }}>
           </div>
         </main>
       </ThemeProvider>
    </body>
      </html>
    )
  }
}

export default Layout;
